services:
  test:
    image: golang:1.27.1-trixie
    working_dir: /app
    volumes:
      - "./:/app"
    networks:
      - nakusp-network
    depends_on:
      - redis
    command:
      - "sh"
      - "-c"
      - "rm -f go.work go.work.sum && go work init . ./transports/redis ./transports/sqlite && go mod download && for mod in . ./transports/redis ./transports/sqlite; do (cd $$mod && go test -v ./...) || exit 1; done"
    stop_signal: SIGINT
    environment:
      REDIS_URI: "redis://redis:6379/0"
  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v2.0.0
    ulimits:
      memlock: -1
    networks:
      - nakusp-network
    restart: unless-stopped
networks:
  nakusp-network:
    driver: bridge

